dashboard/urls.py
from django.urls import path

from . import ajax, views

app_name = "dashboard"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("notifications",
         views.NotificationsView.as_view(),
         name="notifications"),
    path("apply",
         views.NewApplicationFormOneView.as_view(),
         name="application_form_one"),
    path("apply/add-ranks/<int:application_id>",
         views.NewApplicationAddRanksView.as_view(),
         name="application_form_ranks"),
    path("apply/upload/<int:application_id>",
         views.NewApplicationFormOneUploadView.as_view(),
         name="application_form_one_upload"),
    path("apply/upload-signature/<int:application_id>",
         views.UploadSignatureView.as_view(),
         name="upload_signature"),
    path("apply/review/<int:application_id>",
         views.NewApplicationFormOneReviewView.as_view(),
         name="application_form_one_review"),
    path("my-applications",
         views.MyApplicationsView.as_view(),
         name="my_applications"),
    path("submitted-applications",
         views.SubmittedApplicationsView.as_view(),
         name="submitted_applications"),
    path("submitted-application-review/<int:application_id>",
         views.SubmittedApplicationReviewView.as_view(),
         name="submitted_application_review"),
    path("delete-application",
         views.DeleteApplicationView.as_view(),
         name="delete_application"),
    path("application-details/<int:application_id>",
         views.ApplicationDetailsView.as_view(),
         name="application_details"),
    path("application-submission/<int:application_id>",
         views.ApplicationSubmissionView.as_view(),
         name="application_submission"),
    path("application-processed",
         views.ApplicationProcessedView.as_view(),
         name="application_processed"),
    path("request-changes",
         views.RequestApplicationChangesView.as_view(),
         name="request_changes"),
    path("controller-form/<int:application_id>/",
         views.ControllerFormView.as_view(),
         name="controller_form"),
    path("add-pensionable-emolument-before-retirement/<int:application_id>/",
         views.AddPensionableEmolumentDrawnBeforeRetirementView.as_view(),
         name="add_pensionable_emolument_before_retirement"),
    path("add-no-pay-leave/<int:application_id>/",
         views.AddNoPayLeaveView.as_view(),
         name="add_no_pay_leave"),
    path("add-service-break/<int:application_id>/",
         views.AddServiceBreakView.as_view(),
         name="add_service_break"),
    path("add-office-particulars/<int:application_id>/",
         views.AddOfficeParticularsView.as_view(),
         name="add_office_particulars"),
    path("add-paid-open-vote-service/<int:application_id>/",
         views.AddPaidOpenVoteServiceView.as_view(),
         name="add_paid_open_vote_service"),
    path("delete-pensionable-emolument/<int:pk>/",
         views.DeletePensionableEmolumentView.as_view(),
         name="delete_pensionable_emolument"),
    path("delete-no-pay-leave/<int:pk>/",
         views.DeleteNoPayLeaveView.as_view(),
         name="delete_no_pay_leave"),
    path("delete-service-break/<int:pk>/",
         views.DeletServiceBreakView.as_view(),
         name="delete_service_break"),
    path("delete-office-particulars/<int:pk>/",
         views.DeleteOfficeParticularsView.as_view(),
         name="delete_office_particulars"),
    path("delete-paid-open-vote-service/<int:pk>/",
         views.DeletePaidOpenVoteServiceView.as_view(),
         name="delete_paid_open_vote_service"),
    path("resend-sms", views.ResendSMSView.as_view(), name="resend_sms"),
]

urlpatterns += [
    path("ajax/upload-photo",
         ajax.UploadPhotoView.as_view(),
         name="upload_photo"),
    path("ajax/delete-application-document",
         ajax.ApplicationDocumentDeletionView.as_view(),
         name="delete_application_ducument")
]

pdf_engine/urls.py
from django.urls import path

from . import views

app_name = "pdf"

urlpatterns = [
    path("generate-letters/<int:application_id>/",
         views.GenerateLetterView.as_view(),
         name="generate_letter"),
    path("controller-form/<int:application_id>/",
         views.GenerateControllerFormView.as_view(),
         name="controller_form"),
    path("generate-passport-size-photo/<int:application_id>/",
         views.GeneratePassportSizePhotoView.as_view(),
         name="generate_passport_size_photo"),
    path("documents-print-out/<int:application_id>/",
         views.DocumentsPrintOutView.as_view(),
         name="documents_print_out"),
]

setup/urls.py
from django.urls import path

from . import views

app_name = "setup"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("rank/change", views.CreateUpdateRank.as_view(), name="change_rank"),
    path("rank/delete", views.DeleteRank.as_view(), name="delete_rank"),
    path("document-type/change",
         views.CreateUpdateApplicationDocumentType.as_view(),
         name="change_document_type"),
    path("document-type/delete",
         views.DeleteApplicationDocumentType.as_view(),
         name="delete_document_type"),
    path("role/change", views.CreateUpdateGroup.as_view(), name="change_role"),
    path("role/delete", views.DeleteGroup.as_view(), name="delete_role"),
    path("user/delete", views.DeleteUser.as_view(), name="delete_user"),
    path("role/<int:role_id>/manage/",
         views.RoleManagementView.as_view(),
         name="manage_role"),
    path("user/change", views.CreateUpdateUser.as_view(), name="change_user"),
    path("retirement-reason/change",
         views.CreateUpdateRetirementReason.as_view(),
         name="change_retirement_reason"),
    path("retirement-reason/delete",
         views.DeleteRetirementReason.as_view(),
         name="delete_retirement_reason"),
    path("update-sysconfig",
         views.UpdateSysConfigView.as_view(),
         name="update_sysconfig"),
]

dashboard/forms.py
from django import forms

from dashboard.models import (Application, ApplicationRank, OfficeParticulars,
                              PaidOpenVoteService)


class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        exclude = [
            "id",
            "status",
            "created_by",
            "updated_by",
        ]


class ApplicationRankForm(forms.ModelForm):
    class Meta:
        model = ApplicationRank
        exclude = [
            "id",
            'application',
            "created_by",
            "updated_by",
        ]


class OfficeParticularsForm(forms.ModelForm):
    class Meta:
        model = OfficeParticulars
        exclude = [
            "id",
        ]


class PaidOpenVoteServiceForm(forms.ModelForm):
    class Meta:
        model = PaidOpenVoteService
        exclude = [
            "id",
        ]

dashboard/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.utils.html import strip_tags
from django.views import View

from dashboard.forms import ApplicationForm, ApplicationRankForm
from dashboard.models import (Application, ApplicationDocument,
                              ApplicationDocumentType, ApplicationRank,
                              Notification, Rank, Sms)
from dashboard.utils.constants import (APPLICATION_PROCESSED_MESSAGE,
                                       APPLICATION_SUBMISSION_MESSAGE,
                                       APPLICATION_SUBMISSION_SUBJECT)
from dashboard.utils.functions import send_sms
from pension.utils.constants import ApplicationStatus
from setup.models import RetirementReason
import logging

logger = logging.getLogger("django")


class IndexView(View):
    template_name = 'dashboard/index.html'

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request):
        return render(request, self.template_name)


class NotificationsView(View):
    template_name = 'dashboard/notifications.html'

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request):
        context = {
            "sms_list":
            Sms.objects.filter(initiated_by=request.user).order_by('-created_at')
        }
        return render(request, self.template_name, context)


class NewApplicationFormOneView(PermissionRequiredMixin, View):
    """Create and update applications here.
    """
    template_name = 'dashboard/form_one.html'
    form_class = ApplicationForm
    permission_required = ("dashboard.change_application", )

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request):
        application_id = request.GET.get("application_id")
        application = Application.objects.filter(id=application_id).first()
        # Edit only draft and applications in need of changes
        if application and not application.can_edit():
            messages.warning(request, "Editing this application is forbidden.")
            return redirect(
                request.META.get("HTTP_REFERER") or "dashboard:index")

        context = {
            "application": application,
            "ranks": Rank.objects.all(),
            "reasons": RetirementReason.objects.all(),
        }
        return render(request, self.template_name, context)

    @method_decorator(login_required(login_url="accounts:login"))
    def post(self, request):
        application_id = request.GET.get("application_id")
        application = Application.objects.filter(id=application_id).first()

        if application and not application.can_edit():
            messages.warning(request, "Editing this application is forbidden.")
            return redirect(request.META.get("HTTP_REFERER"))

        form = self.form_class(request.POST,
                               request.FILES or None,
                               instance=application)
        if form.is_valid():
            application = form.save(commit=False)
            application.last_updated_by = request.user
            if not application_id:
                application.created_by = request.user
            application.save()
            messages.info(request, "Application has been saved")
            return redirect("dashboard:application_form_one_upload",
                            application.id)
        else:
            for field, error in form.errors.items():
                message = f"{field.title()}: {strip_tags(error)}"
                break
            context = {k: v for k, v in request.POST.items()}
            messages.warning(request, message)
            return render(request, self.template_name, context)


class NewApplicationAddRanksView(PermissionRequiredMixin, View):
    template_name = 'dashboard/form_one_ranks.html'
    form_class = ApplicationRankForm
    permission_required = (
        "dashboard.add_application",
        "dashboard.change_application",
        "dashboard.add_rank",
        "dashboard.change_rank",
    )

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request, application_id):
        application = Application.objects.filter(id=application_id).first()
        ranks = Rank.objects.all()
        context = {"application": application, "ranks": ranks}
        return render(request, self.template_name, context)

    @method_decorator(login_required(login_url="accounts:login"))
    def post(self, request, application_id):
        application_id = request.POST.get("application_id")
        application = get_object_or_404(Application, id=application_id)

        # Process Ranks
        ranks = request.POST.getlist("ranks")
        dates = request.POST.getlist("dates")
        application.ranks.exclude(id__in=ranks).delete()
        for rank, date in zip(ranks, dates):
            rank_obj = ApplicationRank.objects.get_or_create(
                application_id=application_id, rank_id=rank, date=date)[0]
            rank_obj.created_by = request.user
        return redirect("dashboard:application_form_one_upload",
                        application.id)


class NewApplicationFormOneUploadView(PermissionRequiredMixin, View):
    template_name = 'dashboard/form_one_upload.html'
    permission_required = (
        "dashboard.add_applicationdocument",
        "dashboard.change_application",
    )

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request, application_id):
        application = get_object_or_404(Application, id=application_id)
        document_types = ApplicationDocumentType.objects.all()
        context = {
            "application": application,
            "document_types": document_types,
        }
        return render(request, self.template_name, context)

    @method_decorator(login_required(login_url="accounts:login"))
    def post(self, request, application_id):
        document_types = ApplicationDocumentType.objects.all()
        for document_type in document_types:
            files = request.FILES.getlist(document_type.codename)
            for file in files:
                doc = ApplicationDocument.objects.get_or_create(
                    name=document_type.name,
                    document_type=document_type,
                    file=file,
                    application_id=application_id)[0]
                doc.save()
        return redirect(request.META.get("HTTP_REFERER"))


class UploadSignatureView(PermissionRequiredMixin, View):
    permission_required = ("dashboard.change_application", )

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request, application_id):
        return redirect("dashboard:index")

    @method_decorator(login_required(login_url="accounts:login"))
    def post(self, request, application_id):
        application = get_object_or_404(Application, id=application_id)
        signature = request.FILES.get("signature")
        if signature:
            application.signature = signature
            application.save()
            messages.info(request, "Signature has been uploaded")
        else:
            messages.warning(request, "No signature uploaded")
        return redirect(request.META.get("HTTP_REFERER") or "dashboard:index")


class NewApplicationFormOneReviewView(PermissionRequiredMixin, View):
    template_name = 'dashboard/application_review_page.html'
    permission_required = (
        "dashboard.view_application",
        "dashboard.view_applicationrank",
    )

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request, application_id):
        application = get_object_or_404(Application, id=application_id)
        document_types = ApplicationDocumentType.objects.all()
        context = {
            "application": application,
            "document_types": document_types,
        }
        return render(request, self.template_name, context)


class MyApplicationsView(PermissionRequiredMixin, View):
    template_name = 'dashboard/my_applications.html'
    permission_required = "dashboard.view_application"

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request):
        applications = Application.objects.all().order_by("-updated_at")
        context = {"applications": applications}
        return render(request, self.template_name, context)


class SubmittedApplicationsView(PermissionRequiredMixin, View):
    template_name = 'dashboard/submitted_applications.html'
    permission_required = "dashboard.can_review_application"

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request):
        applications = Application.objects.exclude(
            status=ApplicationStatus.DRAFT.value).order_by("-updated_at")
        context = {"applications": applications}
        return render(request, self.template_name, context)


class SubmittedApplicationReviewView(PermissionRequiredMixin, View):
    template_name = 'dashboard/submitted_application_review_page.html'
    permission_required = "dashboard.can_review_application"

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request, application_id):
        application = get_object_or_404(Application, id=application_id)
        if application.status == ApplicationStatus.SUMITTED:
            application.status = ApplicationStatus.PROCESSING.value
            application.save()
        document_types = ApplicationDocumentType.objects.all()
        context = {
            "application": application,
            "document_types": document_types,
        }
        return render(request, self.template_name, context)

dashboard/templates/dashboard/blocks/application_review.html
<div class="p-5 mt-5 card-shadow">
    <h5 class="text">PARTICULARS</h5>
    <div class="col-12 col-md-12 row mt-3">
        <p class="m-0 p-0 text col-md-3  text-muted">Surname:</p>
        <p class="m-0 p-0 text col-md-9 text-primary">{{application.surname}}</p>
    </div>

    <div class="col-12 col-md-12 row mt-3">
        <p class="m-0 p-0 text col-md-3  text-muted">Other Names:</p>
        <p class="m-0 p-0 text col-md-9 text-primary">{{application.other_names}}</p>
    </div>

    <div class="col-12 col-md-12 row mt-3">
        <p class="m-0 p-0 text col-md-3  text-muted">Rank:</p>
        <p class="m-0 p-0 text col-md-9 text-primary">{{application.rank}}</p>
    </div>

    <div class="col-12 col-md-12 row mt-3">
        <p class="m-0 p-0 text col-md-3  text-muted">Retiring Date:</p>
        <p class="m-0 p-0 text col-md-9 text-primary">{{application.retiring_date}}</p>
    </div>

    <div class="col-12 col-md-12 row mt-3">
        <p class="m-0 p-0 text col-md-3  text-muted">Reason:</p>
        <p class="m-0 p-0 text col-md-9 text-primary">{{application.reason}}</p>
    </div>

    <div class="col-12 col-md-12 row mt-3">
        <p class="m-0 p-0 text col-md-3  text-muted">Bank Name:</p>
        <p class="m-0 p-0 text col-md-9 text-primary">{{application.bank_name}}</p>
    </div>

    <div class="col-12 col-md-12 row mt-3">
        <p class="m-0 p-0 text col-md-3  text-muted">Bank Account Number:</p>
        <p class="m-0 p-0 text col-md-9 text-primary">{{application.bank_account}}</p>
    </div>

    <div class="col-12 col-md-12 row mt-3">
        <p class="m-0 p-0 text col-md-3  text-muted">Last Station:</p>
        <p class="m-0 p-0 text col-md-9 text-primary">{{application.last_station}}</p>
    </div>

    <div class="col-12 col-md-12 row mt-3">
        <p class="m-0 p-0 text col-md-3  text-muted">Region:</p>
        <p class="m-0 p-0 text col-md-9 text-primary">{{application.region}}</p>
    </div>

    <div class="col-12 col-md-12 row mt-3">
        <p class="m-0 p-0 text col-md-3  text-muted">Contact:</p>
        <p class="m-0 p-0 text col-md-9 text-primary">{{application.contact}}</p>
    </div>

    <div class="col-12 col-md-12 row mt-3">
        <p class="m-0 p-0 text col-md-3  text-muted">Contact Address:</p>
        <p class="m-0 p-0 text col-md-9 text-primary">{{application.contact_address}}</p>
    </div>

    <div class="col-12 col-md-12 row mt-3">
        <p class="m-0 p-0 text col-md-3  text-muted">Status:</p>
        <p class="m-0 p-0 text col-md-9 text-primary">{{application.status}}</p>
    </div>

    <div class="col-12 col-md-12 row mt-3">
        <p class="m-0 p-0 text col-md-3  text-muted">Date:</p>
        <p class="m-0 p-0 text col-md-9 text-primary">{{application.created_at|date}}</p>
    </div>

</div>

<div class="p-5 mt-5 card-shadow">
    <h5 class="text">APPLICANT'S PHOTO</h5>
    {% if application.photo %}
    <div class="col-md-6 mx-auto">
        <img height="300" src="{{application.photo.url}}" alt="">
    </div>
    {% else %}
    <p class="text text-danger">None</p>
    {% endif %}
</div>
{% if application.photo %}
<div class="d-flex justify-content-end">
    <a href="{% url 'pdf:generate_passport_size_photo' application.id %}" target="_blank" class="btn btn-primary my-2"><i
            class="bi bi-printer"></i> Print Passport Size</a>
</div>
{% endif %}


<div class="p-5 mt-5 card-shadow">
    <h5 class="text">ATTACHMENTS</h5>
    {% if application.documents.all %}
    {% for document_type in document_types %}
    <div class="row mb-3">
        <h4 class="text text-primary">{{document_type.name}}</h4>
        {% for document in application.documents.all %}
        {% if document.document_type == document_type %}
        <a href="{{document.file.url}}" class="col-md-4"
            style="border: 1px solid rgba(128, 128, 128, 0.1); display: flex; align-items: center;">
            <img class="mx-auto" height="200" src="{{document.file.url}}" alt="{{document.name}}"
                style="max-width: 100%;">
        </a>
        {% endif %}
        {% endfor %}
    </div>
    {% endfor %}
    {% else %}
    <p class="text text-danger">None</p>
    {% endif %}
</div>
{% if application.documents.all %}
<div class="d-flex justify-content-end">
    <a href="{% url 'pdf:documents_print_out' application.id %}" target="_blank" class="btn btn-primary my-2"><i
            class="bi bi-printer"></i> Print All</a>
</div>
{% endif %}


<div class="p-5 mt-5 card-shadow">
    <h5 class="text">SIGNATURE</h5>
    {% if application.signature %}
    <p class="text text-center">
        <a href="{{application.signature.url}}" target="_blank">
            <img height="200" src="{{application.signature.url}}" alt="Applicant's signature">
        </a>
    </p>
    {% else %}
    <p class="text text-danger">None</p>
    {% endif %}
</div>

dashboard/templates/dashboard/blocks/application_status.html
{% if application.status == 'draft' or application.status == 'processing' or application.status == 'submitted' %}
<span class="badge bg-info">{{application.get_status}}</span>
{% elif  application.status == 'processed'  %}
<span class="badge bg-success">{{application.get_status}}</span>
{% elif  application.status == 'requested_changes'  %}
<span class="badge bg-danger">{{application.get_status}}</span>
{% endif %}