setup/urls.py
from django.urls import path

from . import views

app_name = "setup"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("rank/change", views.CreateUpdateRank.as_view(), name="change_rank"),
    path("rank/delete", views.DeleteRank.as_view(), name="delete_rank"),
    path("document-type/change",
         views.CreateUpdateApplicationDocumentType.as_view(),
         name="change_document_type"),
    path("document-type/delete",
         views.DeleteApplicationDocumentType.as_view(),
         name="delete_document_type"),
    path("role/change", views.CreateUpdateGroup.as_view(), name="change_role"),
    path("role/delete", views.DeleteGroup.as_view(), name="delete_role"),
    path("user/delete", views.DeleteUser.as_view(), name="delete_user"),
    path("role/<int:role_id>/manage/",
         views.RoleManagementView.as_view(),
         name="manage_role"),
    path("user/change", views.CreateUpdateUser.as_view(), name="change_user"),
    path("retirement-reason/change",
         views.CreateUpdateRetirementReason.as_view(),
         name="change_retirement_reason"),
    path("retirement-reason/delete",
         views.DeleteRetirementReason.as_view(),
         name="delete_retirement_reason"),
    path("update-sysconfig",
         views.UpdateSysConfigView.as_view(),
         name="update_sysconfig"),
]

setup/models.py
from django.db import models


# Just for permissions
class SetupPerms(models.Model):
    class Meta:
        managed = False  # No database table creation or deletion  \
        # operations will be performed for this model.
        default_permissions = ()  # disable "add", "change", "delete"
        # and "view" default permissions
        permissions = (('can_setup_system', 'Can Setup System'),
                       ("can_managemnt_roles",
                        "Can Management role assignment user groups."))


class ApplicationDocumentType(models.Model):
    name = models.CharField(max_length=50)
    required = models.BooleanField(default=True)
    multiple = models.BooleanField(default=True)
    codename = models.CharField(max_length=50, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.codename:
            self.codename = "_".join(self.name.lower().split())
        return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name


class Rank(models.Model):
    name = models.CharField(max_length=100, unique=True)
    abbreviation = models.CharField(max_length=20, default="")
    order = models.IntegerField()

    def save(self, *args, **kwargs):
        if not self.abbreviation:
            self.abbreviation = self.name[:3].upper()
        return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name


class RetirementReason(models.Model):
    reason = models.TextField()
    description = models.TextField(null=True, blank=True)

    def __str__(self) -> str:
        return self.reason


class SysConfig(models.Model):
    sms_sender_id = models.CharField(max_length=11,
                                     unique=True,
                                     default="GHPOLPEN")
    send_sms = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.name

setup/forms.py
from django import forms
from django.contrib.auth.models import Group

from accounts.models import User
from setup.models import ApplicationDocumentType, Rank, RetirementReason


class RankForm(forms.ModelForm):
    class Meta:
        model = Rank
        exclude = [
            "id",
        ]


class ApplicationDocumentTypeForm(forms.ModelForm):
    class Meta:
        model = ApplicationDocumentType
        exclude = [
            "id",
            'codename',
            "created_at",
            "updated_at",
        ]


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = [
            'name',
        ]


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        exclude = [
            "id",
            'photo',
            'email',
            'gender',
            'password',
            'last_login',
            "created_at",
            "updated_at",
        ]


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        exclude = [
            "id",
            'photo',
            'email',
            'password',
            "username",
            'gender',
            'last_login',
            "created_at",
            "updated_at",
        ]


class RetirementReasonForm(forms.ModelForm):
    class Meta:
        model = RetirementReason
        exclude = [
            "id",
        ]

setup/views.py
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import Group, Permission
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.views import View

from accounts.models import User
from setup.forms import (ApplicationDocumentTypeForm, GroupForm, RankForm,
                         RetirementReasonForm, UserEditForm, UserForm)
from setup.models import (ApplicationDocumentType, Rank, RetirementReason,
                          SysConfig)
from setup.mxins import CreateUpdateMixin, DeletionMixin


class IndexView(PermissionRequiredMixin, View):
    template_name = "setup/index.html"
    permission_required = ("setup.can_setup_system", )

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request):
        document_types = ApplicationDocumentType.objects.all()
        ranks = Rank.objects.all().order_by("order")
        roles = Group.objects.all()
        users = User.objects.filter(is_superuser=False)
        reasons = RetirementReason.objects.all()
        config = SysConfig.objects.first()

        context = {
            "document_types": document_types,
            "ranks": ranks,
            "roles": roles,
            "config": config,
            "users": users,
            "reasons": reasons,
            "user": None,
        }
        return render(request, self.template_name, context)


class CreateUpdateRank(PermissionRequiredMixin, CreateUpdateMixin):
    template_name = "setup/edit_rank.html"
    form_class = RankForm
    object_id_field = "rank_id"
    model_class = Rank
    object_name = "rank"
    permission_required = (
        "setup.can_setup_system",
        "setup.add_rank",
        "setup.change_rank",
    )


class DeleteRank(PermissionRequiredMixin, DeletionMixin):
    object_id_field = "rank_id"
    model_class = Rank
    permission_required = (
        "setup.can_setup_system",
        "setup.delete_rank",
    )


class CreateUpdateApplicationDocumentType(PermissionRequiredMixin,
                                          CreateUpdateMixin):
    template_name = "setup/edit_application_document_type.html"
    form_class = ApplicationDocumentTypeForm
    object_id_field = "document_type_id"
    model_class = ApplicationDocumentType
    object_name = "document_type"
    permission_required = (
        "setup.can_setup_system",
        "setup.add_applicationdocumenttype",
        "setup.change_applicationdocumenttype",
    )


class DeleteApplicationDocumentType(PermissionRequiredMixin, DeletionMixin):
    object_id_field = "document_type_id"
    model_class = ApplicationDocumentType
    permission_required = (
        "setup.can_setup_system",
        "setup.delete_applicationdocumenttype",
    )


class CreateUpdateGroup(PermissionRequiredMixin, CreateUpdateMixin):
    template_name = "setup/edit_role.html"
    form_class = GroupForm
    object_id_field = "role_id"
    model_class = Group
    object_name = "role"
    permission_required = (
        "setup.can_setup_system",
        "auth.add_group",
        "auth.change_group",
    )


class DeleteGroup(PermissionRequiredMixin, DeletionMixin):
    object_id_field = "role_id"
    model_class = Group
    permission_required = (
        "setup.can_setup_system",
        "auth.delete_group",
    )


class DeleteUser(PermissionRequiredMixin, DeletionMixin):
    object_id_field = "user_id"
    model_class = User
    permission_required = (
        "setup.can_setup_system",
        "accounts.delete_user",
    )


class RoleManagementView(PermissionRequiredMixin, View):
    template_name = "setup/role_management.html"
    permission_required = (
        "setup.can_managemnt_roles",
        "setup.can_setup_system",
    )

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request, role_id):
        role = get_object_or_404(Group, id=role_id)
        permissions = Permission.objects.filter()[:0]
        apps_list = [app.split(".")[0] for app in settings.INSTALLED_APPS]
        models = []
        for app in apps_list:
            models.extend([
                model._meta.model_name
                for _, model in apps.all_models[app].items()
            ])
        permissions = Permission.objects.filter(
            content_type__app_label__in=apps_list,
            content_type__model__in=models)
        permissions = Permission.objects.all()
        context = {
            "role": role,
            "permissions": permissions,
        }
        return render(request, self.template_name, context)

    @method_decorator(login_required(login_url="accounts:login"))
    def post(self, request, role_id):
        role = get_object_or_404(Group, id=role_id)
        permissions_codes = request.POST.getlist("permissions")
        permissions = Permission.objects.filter(codename__in=permissions_codes)
        role.permissions.set(permissions)
        return redirect(request.META.get("HTTP_REFERER") or "setup:dashboard")


class CreateUpdateUser(PermissionRequiredMixin, CreateUpdateMixin):
    template_name = "setup/edit_user.html"
    object_id_field = "user_id"
    form_class = UserForm
    edit_form_class = UserEditForm
    model_class = User
    object_name = "user"
    permission_required = (
        "setup.can_setup_system",
        "accounts.add_user",
        "accounts.change_user",
    )

    def get(self, request):
        object_id = request.GET.get(self.object_id_field)
        obj = get_object_or_404(self.model_class, id=object_id)
        roles = Group.objects.all()
        context = {
            self.object_name: obj,
            "roles": roles,
        }
        return render(request, self.template_name, context)

    @method_decorator(login_required(login_url="accounts:login"))
    def post(self, request):
        user_id = request.POST.get("user_id") or None
        password = request.POST.get("password")
        username = request.POST.get("username")
        group_ids = request.POST.getlist("groups")
        conf_password = request.POST.get("conf_password")

        groups = Group.objects.filter(id__in=group_ids)

        if password and password != conf_password:
            messages.error(request, "Passwords do not match")
            return redirect(request.META.get("HTTP_REFERER") or "setup:index")

        user = User.objects.filter(
            id=user_id).first() or User.objects.create_user(username=username,
                                                            password=password)
        # Add to groups
        user.groups.set(groups)

        # Update fields
        for key, value in request.POST.items():
            if key in ["password", "username", "groups"]: continue
            if value and key and hasattr(user, key):
                setattr(user, key, value)
        if password: user.set_password(password)
        user.save()
        messages.success(request, "User updated successfully")
        return redirect("setup:index")


class CreateUpdateRetirementReason(PermissionRequiredMixin, CreateUpdateMixin):
    template_name = "setup/edit_retirement_reason.html"
    form_class = RetirementReasonForm
    object_id_field = "retirement_reason_id"
    model_class = RetirementReason
    object_name = "retirement_reason"
    permission_required = (
        "setup.can_setup_system",
        "setup.add_retirementreason",
        "setup.change_retirementreason",
    )


class DeleteRetirementReason(PermissionRequiredMixin, DeletionMixin):
    object_id_field = "retirement_reason_id"
    model_class = RetirementReason
    permission_required = (
        "setup.can_setup_system",
        "setup.delete_retirement_reason",
    )


class UpdateSysConfigView(PermissionRequiredMixin, View):
    permission_required = ("setup.can_setup_system", )

    def get(self, request, *args, **kwargs):
        return redirect("setup:index")

    @method_decorator(login_required(login_url="accounts:login"))
    def post(self, request, *args, **kwargs):
        config = SysConfig.objects.first()
        if "sms_sender_id" in request.POST and not "send_sms" in request.POST:
            config.send_sms = False
            config.save()
        for key, value in request.POST.items():
            if key in ["csrfmiddlewaretoken", "submit"]: continue
            if key == "send_sms":
                value = True if value == "on" else False
            if value and hasattr(config, key):
                setattr(config, key, value)
        config.save()
        messages.success(request, "System configuration updated successfully")
        return redirect("setup:index")

setup/templates/setup/blocks/forms/form_document_type.html
<form action="{% url 'setup:change_document_type' %}" class="needs-validation my-4" method="POST" novalidate>
    {% csrf_token %}
    <input type="hidden" name="document_type_id" value="{{document_type.id}}">
    <div class="form-group">
        <label for="name">Name</label>
        <input class="form-control" placeholder="Pay Slips" value="{{document_type.name}}" type="text" name="name"
            id="name" required>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>

    <div class="my-2 form-group row">
        <label for="required" class="col-md-6">Required</label>
        <input type="checkbox" class="col-md-6" name="required" id="required"
            {% if document_type.required %}checked{% endif %}>
    </div>

    <div class="my-2 form-group row">
        <label for="multiple" class="col-md-6">Allow Mutiple Documents</label>
        <input type="checkbox" class="col-md-6" name="multiple" id="multiple"
            {% if document_type.multiple %}checked{% endif %}>
    </div>
    <div class="form-group my-3">
        <button type="submit" class="btn btn-primary py-2 px-4">Submit</button>
    </div>
</form>

setup/templates/setup/blocks/forms/form_rank.html
<form action="{% url 'setup:change_rank' %}" class="needs-validation my-4" method="POST" novalidate>
    {% csrf_token %}
    <input type="hidden" name="rank_id" value="{{rank.id}}">
    <div class="row">
        <div class="col-md-6 form-group">
            <label for="name">Name</label>
            <input class="form-control" placeholder="Chief Inspector" value="{{rank.name}}" type="text" name="name"
                id="name" required>
            <div class="invalid-feedback">
                Please this field is required.
            </div>
        </div>
        <div class="col-md-6 form-group">
            <label for="name">Abbreviation</label>
            <input class="form-control" placeholder="C. Ins." value="{{rank.abbreviation}}" type="text"
                name="abbreviation" id="abbreviation">
            <div class="invalid-feedback">
                Please this field is required.
            </div>
        </div>
        <div class="col-md-6 form-group">
            <label for="order">Order</label>
            <input class="form-control" type="number" placeholder="1" value="{{rank.order}}" name="order" id="order"
                required>
            <div class="invalid-feedback">
                Please this field is required.
            </div>
        </div>
    </div>
    <div class="form-group my-3">
        <button type="submit" class="btn btn-primary py-2 px-4">Submit</button>
    </div>
</form>

setup/templates/setup/blocks/forms/form_retirement_reason.html
<form action="{% url 'setup:change_retirement_reason' %}" class="needs-validation my-4" method="POST" novalidate>
    {% csrf_token %}
    <input type="hidden" name="retirement_reason_id" value="{{retirement_reason.id}}">
    <div class="row">
        <div class="col-12 form-group">
            <label for="name">Retirement Reason <span class="text text-danger">*</span> </label>
            <input class="form-control" placeholder="Reason" value="{{retirement_reason.reason}}" type="text"
                name="reason" id="reason" required>
            <div class="invalid-feedback">
                Please this field is required.
            </div>
        </div>
        <div class="col-12 form-group mt-3">
            <label for="name">Description (Optional)</label>
            <textarea class="form-control" name="description" id="description" rows="10">{{retirement_reason.description}}</textarea>
        </div>
    </div>
    <div class="form-group my-3">
        <button type="submit" class="btn btn-primary py-2 px-4">Submit</button>
    </div>
</form>

setup/templates/setup/blocks/forms/form_role.html
<form action="{% url 'setup:change_role' %}" class="needs-validation my-4" method="POST" novalidate>
    {% csrf_token %}
    <input type="hidden" name="role_id" value="{{role.id}}">
    <div class="form-group">
        <label for="name">Name</label>
        <input class="form-control" placeholder="Regional" value="{{role.name}}" type="text" name="name" id="name"
            required>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>
    <div class="form-group my-3">
        <button type="submit" class="btn btn-primary py-2 px-4">Submit</button>
    </div>
</form>

setup/templates/setup/blocks/forms/form_user.html
<form action="{% url 'setup:change_user' %}" class="needs-validation my-4" method="POST" novalidate>
    {% csrf_token %}
    <input type="hidden" name="user_id" value="{{user.id}}">
    <div class="form-group mt-3">
        <label for="username">Username <span class="text text-danger">*</span></label>
        <input class="form-control" placeholder="johndoe" {% if user %} disabled {% endif %} required name="username"
            type="text" id="username" value="{{user.username}}">
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>

    <div class="form-group mt-3">
        <label for="surname">Surname <span class="text text-danger">*</span></label>
        <input class="form-control" placeholder="Mensah" value="{{user.surname}}" type="text" name="surname"
            id="surname" required>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>

    <div class="form-group mt-3">
        <label for="other_names">Other Names <span class="text text-danger">*</span></label>
        <input class="form-control" placeholder="Mensah" value="{{user.other_names}}" type="text" name="other_names"
            id="other_names" required>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>

    <div class="form-group mt-3">
        <label for="phone">Phone<span class="text text-danger">*</span></label>
        <input class="form-control" minlength="10" maxlength="10" placeholder="0240000000" value="{{user.phone}}"
            type="text" name="phone" id="phone" required>
        <div class="invalid-feedback">
            Please enter a valid 10 digit phone number.
        </div>
    </div>


    <div class="form-group mt-3">
        <label for="groups">Group/Role</label>
        <br>
        <small class="text text-info">Hold down Ctrl/Cmd to select multiple.</small>
        <select class="form-select" name="groups" id="groups" multiple aria-label="multiple select groups/roles">
            {% for role in roles %}
            <option value="{{role.id}}" {% if role in user.groups.all %}selected{% endif %}>{{role.name}}</option>
            {% endfor %}
        </select>
    </div>

    <div class="form-group mt-3">
        <label for="region">Region <span class="text text-danger">*</span></label>
        <select name="region" id="region" class="form-control" required>
            <option value="">---Click to select region---</option>
            <option value="AHAFO" {% if user.region == 'AHAFO' %}selected{%endif%}>AHAFO</option>
            <option value="ASHANTI" {% if user.region == 'ASHANTI' %}selected{%endif%}>ASHANTI</option>
            <option value="BONO EAST" {% if user.region == 'BONO EAST' %}selected{%endif%}>BONO EAST</option>
            <option value="BRONG AHAFO" {% if user.region == 'BRONG AHAFO' %}selected{%endif%}>BRONG AHAFO</option>
            <option value="CENTRAL" {% if user.region == 'CENTRAL' %}selected{%endif%}>CENTRAL</option>
            <option value="EASTERN" {% if user.region == 'EASTERN' %}selected{%endif%}>EASTERN</option>
            <option value="GREATER ACCRA" {% if user.region == 'GREATER ACCRA' %}selected{%endif%}>GREATER ACCRA</option>
            <option value="NORTH EAST" {% if user.region == 'NORTH EAST' %}selected{%endif%}>NORTH EAST</option>
            <option value="NORTHERN" {% if user.region == 'NORTHERN' %}selected{%endif%}>NORTHERN</option>
            <option value="OTI" {% if user.region == 'OTI' %}selected{%endif%}>OTI</option>
            <option value="SAVANNAH" {% if user.region == 'SAVANNAH' %}selected{%endif%}>SAVANNAH</option>
            <option value="UPPER EAST" {% if user.region == 'UPPER EAST' %}selected{%endif%}>UPPER EAST</option>
            <option value="UPPER WEST" {% if user.region == 'UPPER WEST' %}selected{%endif%}>UPPER WEST</option>
            <option value="WESTERN" {% if user.region == 'WESTERN' %}selected{%endif%}>WESTERN</option>
            <option value="WESTERN NORTH" {% if user.region == 'WESTERN NORTH' %}selected{%endif%}>WESTERN NORTH</option>
            <option value="VOLTA" {% if user.region == 'VOLTA' %}selected{%endif%}>VOLTA</option>
        </select>
    </div>

    <h6 class="text text-primary mt-5">{% if user %}CHANGE{% else %}SET{% endif %} PASSWORD</h6>
    <div class="form-group">
        <label for="name">Password <span class="text text-danger">*</span></label>
        <input class="form-control" placeholder="**********" type="password" name="password" id="password"
            {% if not user %}required{% endif %}>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>
    <div class="form-group">
        <label for="name">Confirm Password <span class="text text-danger">*</span></label>
        <input class="form-control" placeholder="**********" type="password" name="conf_password" id="password"
            {% if not user %}required{% endif %}>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>

    <div class="form-group my-3">
        <button type="submit" class="btn btn-primary py-2 px-4">Submit</button>
    </div>
</form>