accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
]

dashboard/urls.py
from django.urls import path

from . import ajax, views

app_name = "dashboard"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("notifications",
         views.NotificationsView.as_view(),
         name="notifications"),
    path("apply",
         views.NewApplicationFormOneView.as_view(),
         name="application_form_one"),
    path("apply/add-ranks/<int:application_id>",
         views.NewApplicationAddRanksView.as_view(),
         name="application_form_ranks"),
    path("apply/upload/<int:application_id>",
         views.NewApplicationFormOneUploadView.as_view(),
         name="application_form_one_upload"),
    path("apply/upload-signature/<int:application_id>",
         views.UploadSignatureView.as_view(),
         name="upload_signature"),
    path("apply/review/<int:application_id>",
         views.NewApplicationFormOneReviewView.as_view(),
         name="application_form_one_review"),
    path("my-applications",
         views.MyApplicationsView.as_view(),
         name="my_applications"),
    path("submitted-applications",
         views.SubmittedApplicationsView.as_view(),
         name="submitted_applications"),
    path("submitted-application-review/<int:application_id>",
         views.SubmittedApplicationReviewView.as_view(),
         name="submitted_application_review"),
    path("delete-application",
         views.DeleteApplicationView.as_view(),
         name="delete_application"),
    path("application-details/<int:application_id>",
         views.ApplicationDetailsView.as_view(),
         name="application_details"),
    path("application-submission/<int:application_id>",
         views.ApplicationSubmissionView.as_view(),
         name="application_submission"),
    path("application-processed",
         views.ApplicationProcessedView.as_view(),
         name="application_processed"),
    path("request-changes",
         views.RequestApplicationChangesView.as_view(),
         name="request_changes"),
    path("controller-form/<int:application_id>/",
         views.ControllerFormView.as_view(),
         name="controller_form"),
    path("add-pensionable-emolument-before-retirement/<int:application_id>/",
         views.AddPensionableEmolumentDrawnBeforeRetirementView.as_view(),
         name="add_pensionable_emolument_before_retirement"),
    path("add-no-pay-leave/<int:application_id>/",
         views.AddNoPayLeaveView.as_view(),
         name="add_no_pay_leave"),
    path("add-service-break/<int:application_id>/",
         views.AddServiceBreakView.as_view(),
         name="add_service_break"),
    path("add-office-particulars/<int:application_id>/",
         views.AddOfficeParticularsView.as_view(),
         name="add_office_particulars"),
    path("add-paid-open-vote-service/<int:application_id>/",
         views.AddPaidOpenVoteServiceView.as_view(),
         name="add_paid_open_vote_service"),
    path("delete-pensionable-emolument/<int:pk>/",
         views.DeletePensionableEmolumentView.as_view(),
         name="delete_pensionable_emolument"),
    path("delete-no-pay-leave/<int:pk>/",
         views.DeleteNoPayLeaveView.as_view(),
         name="delete_no_pay_leave"),
    path("delete-service-break/<int:pk>/",
         views.DeletServiceBreakView.as_view(),
         name="delete_service_break"),
    path("delete-office-particulars/<int:pk>/",
         views.DeleteOfficeParticularsView.as_view(),
         name="delete_office_particulars"),
    path("delete-paid-open-vote-service/<int:pk>/",
         views.DeletePaidOpenVoteServiceView.as_view(),
         name="delete_paid_open_vote_service"),
    path("resend-sms", views.ResendSMSView.as_view(), name="resend_sms"),
]

urlpatterns += [
    path("ajax/upload-photo",
         ajax.UploadPhotoView.as_view(),
         name="upload_photo"),
    path("ajax/delete-application-document",
         ajax.ApplicationDocumentDeletionView.as_view(),
         name="delete_application_ducument")
]

pdf_engine/urls.py
from django.urls import path

from . import views

app_name = "pdf"

urlpatterns = [
    path("generate-letters/<int:application_id>/",
         views.GenerateLetterView.as_view(),
         name="generate_letter"),
    path("controller-form/<int:application_id>/",
         views.GenerateControllerFormView.as_view(),
         name="controller_form"),
    path("generate-passport-size-photo/<int:application_id>/",
         views.GeneratePassportSizePhotoView.as_view(),
         name="generate_passport_size_photo"),
    path("documents-print-out/<int:application_id>/",
         views.DocumentsPrintOutView.as_view(),
         name="documents_print_out"),
]

setup/urls.py
from django.urls import path

from . import views

app_name = "setup"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("rank/change", views.CreateUpdateRank.as_view(), name="change_rank"),
    path("rank/delete", views.DeleteRank.as_view(), name="delete_rank"),
    path("document-type/change",
         views.CreateUpdateApplicationDocumentType.as_view(),
         name="change_document_type"),
    path("document-type/delete",
         views.DeleteApplicationDocumentType.as_view(),
         name="delete_document_type"),
    path("role/change", views.CreateUpdateGroup.as_view(), name="change_role"),
    path("role/delete", views.DeleteGroup.as_view(), name="delete_role"),
    path("user/delete", views.DeleteUser.as_view(), name="delete_user"),
    path("role/<int:role_id>/manage/",
         views.RoleManagementView.as_view(),
         name="manage_role"),
    path("user/change", views.CreateUpdateUser.as_view(), name="change_user"),
    path("retirement-reason/change",
         views.CreateUpdateRetirementReason.as_view(),
         name="change_retirement_reason"),
    path("retirement-reason/delete",
         views.DeleteRetirementReason.as_view(),
         name="delete_retirement_reason"),
    path("update-sysconfig",
         views.UpdateSysConfigView.as_view(),
         name="update_sysconfig"),
]

dashboard/forms.py
from django import forms

from dashboard.models import (Application, ApplicationRank, OfficeParticulars,
                              PaidOpenVoteService)


class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        exclude = [
            "id",
            "status",
            "created_by",
            "updated_by",
        ]


class ApplicationRankForm(forms.ModelForm):
    class Meta:
        model = ApplicationRank
        exclude = [
            "id",
            'application',
            "created_by",
            "updated_by",
        ]


class OfficeParticularsForm(forms.ModelForm):
    class Meta:
        model = OfficeParticulars
        exclude = [
            "id",
        ]


class PaidOpenVoteServiceForm(forms.ModelForm):
    class Meta:
        model = PaidOpenVoteService
        exclude = [
            "id",
        ]

dashboard/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.utils.html import strip_tags
from django.views import View

from dashboard.forms import ApplicationForm, ApplicationRankForm
from dashboard.models import (Application, ApplicationDocument,
                              ApplicationDocumentType, ApplicationRank,
                              Notification, Rank, Sms)
from dashboard.utils.constants import (APPLICATION_PROCESSED_MESSAGE,
                                       APPLICATION_SUBMISSION_MESSAGE,
                                       APPLICATION_SUBMISSION_SUBJECT)
from dashboard.utils.functions import send_sms
from pension.utils.constants import ApplicationStatus
from setup.models import RetirementReason
import logging

logger = logging.getLogger("django")


class IndexView(View):
    template_name = 'dashboard/index.html'

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request):
        return render(request, self.template_name)


class NotificationsView(View):
    template_name = 'dashboard/notifications.html'

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request):
        context = {
            "sms_list":
            Sms.objects.filter(initiated_by=request.user).order_by('-created_at')
        }
        return render(request, self.template_name, context)


class NewApplicationFormOneView(PermissionRequiredMixin, View):
    """Create and update applications here.
    """
    template_name = 'dashboard/form_one.html'
    form_class = ApplicationForm
    permission_required = ("dashboard.change_application", )

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request):
        application_id = request.GET.get("application_id")
        application = Application.objects.filter(id=application_id).first()
        # Edit only draft and applications in need of changes
        if application and not application.can_edit():
            messages.warning(request, "Editing this application is forbidden.")
            return redirect(
                request.META.get("HTTP_REFERER") or "dashboard:index")

        context = {
            "application": application,
            "ranks": Rank.objects.all(),
            "reasons": RetirementReason.objects.all(),
        }
        return render(request, self.template_name, context)

    @method_decorator(login_required(login_url="accounts:login"))
    def post(self, request):
        application_id = request.GET.get("application_id")
        application = Application.objects.filter(id=application_id).first()

        if application and not application.can_edit():
            messages.warning(request, "Editing this application is forbidden.")
            return redirect(request.META.get("HTTP_REFERER"))

        form = self.form_class(request.POST,
                               request.FILES or None,
                               instance=application)
        if form.is_valid():
            application = form.save(commit=False)
            application.last_updated_by = request.user
            if not application_id:
                application.created_by = request.user
            application.save()
            messages.info(request, "Application has been saved")
            return redirect("dashboard:application_form_one_upload",
                            application.id)
        else:
            for field, error in form.errors.items():
                message = f"{field.title()}: {strip_tags(error)}"
                break
            context = {k: v for k, v in request.POST.items()}
            messages.warning(request, message)
            return render(request, self.template_name, context)


class NewApplicationAddRanksView(PermissionRequiredMixin, View):
    template_name = 'dashboard/form_one_ranks.html'
    form_class = ApplicationRankForm
    permission_required = (
        "dashboard.add_application",
        "dashboard.change_application",
        "dashboard.add_rank",
        "dashboard.change_rank",
    )

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request, application_id):
        application = Application.objects.filter(id=application_id).first()
        ranks = Rank.objects.all()
        context = {"application": application, "ranks": ranks}
        return render(request, self.template_name, context)

    @method_decorator(login_required(login_url="accounts:login"))
    def post(self, request, application_id):
        application_id = request.POST.get("application_id")
        application = get_object_or_404(Application, id=application_id)

        # Process Ranks
        ranks = request.POST.getlist("ranks")
        dates = request.POST.getlist("dates")
        application.ranks.exclude(id__in=ranks).delete()
        for rank, date in zip(ranks, dates):
            rank_obj = ApplicationRank.objects.get_or_create(
                application_id=application_id, rank_id=rank, date=date)[0]
            rank_obj.created_by = request.user
        return redirect("dashboard:application_form_one_upload",
                        application.id)


class NewApplicationFormOneUploadView(PermissionRequiredMixin, View):
    template_name = 'dashboard/form_one_upload.html'
    permission_required = (
        "dashboard.add_applicationdocument",
        "dashboard.change_application",
    )

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request, application_id):
        application = get_object_or_404(Application, id=application_id)
        document_types = ApplicationDocumentType.objects.all()
        context = {
            "application": application,
            "document_types": document_types,
        }
        return render(request, self.template_name, context)

    @method_decorator(login_required(login_url="accounts:login"))
    def post(self, request, application_id):
        document_types = ApplicationDocumentType.objects.all()
        for document_type in document_types:
            files = request.FILES.getlist(document_type.codename)
            for file in files:
                doc = ApplicationDocument.objects.get_or_create(
                    name=document_type.name,
                    document_type=document_type,
                    file=file,
                    application_id=application_id)[0]
                doc.save()
        return redirect(request.META.get("HTTP_REFERER"))


class UploadSignatureView(PermissionRequiredMixin, View):
    permission_required = ("dashboard.change_application", )

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request, application_id):
        return redirect("dashboard:index")

    @method_decorator(login_required(login_url="accounts:login"))
    def post(self, request, application_id):
        application = get_object_or_404(Application, id=application_id)
        signature = request.FILES.get("signature")
        if signature:
            application.signature = signature
            application.save()
            messages.info(request, "Signature has been uploaded")
        else:
            messages.warning(request, "No signature uploaded")
        return redirect(request.META.get("HTTP_REFERER") or "dashboard:index")


class NewApplicationFormOneReviewView(PermissionRequiredMixin, View):
    template_name = 'dashboard/application_review_page.html'
    permission_required = (
        "dashboard.view_application",
        "dashboard.view_applicationrank",
    )

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request, application_id):
        application = get_object_or_404(Application, id=application_id)
        document_types = ApplicationDocumentType.objects.all()
        context = {
            "application": application,
            "document_types": document_types,
        }
        return render(request, self.template_name, context)


class MyApplicationsView(PermissionRequiredMixin, View):
    template_name = 'dashboard/my_applications.html'
    permission_required = "dashboard.view_application"

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request):
        applications = Application.objects.all().order_by("-updated_at")
        context = {"applications": applications}
        return render(request, self.template_name, context)


class SubmittedApplicationsView(PermissionRequiredMixin, View):
    template_name = 'dashboard/submitted_applications.html'
    permission_required = "dashboard.can_review_application"

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request):
        applications = Application.objects.exclude(
            status=ApplicationStatus.DRAFT.value).order_by("-updated_at")
        context = {"applications": applications}
        return render(request, self.template_name, context)


class SubmittedApplicationReviewView(PermissionRequiredMixin, View):
    template_name = 'dashboard/submitted_application_review_page.html'
    permission_required = "dashboard.can_review_application"

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request, application_id):
        application = get_object_or_404(Application, id=application_id)
        if application.status == ApplicationStatus.SUMITTED:
            application.status = ApplicationStatus.PROCESSING.value
            application.save()
        document_types = ApplicationDocumentType.objects.all()
        context = {
            "application": application,
            "document_types": document_types,
        }
        return render(request, self.template_name, context)

dashboard/templates/dashboard/application_review_page.html
{% extends 'dashboard/base.html' %}
{% block pagetitle %}New Application{%endblock%}

{% block breadcrum %}
<a href="/" class="item">Home <i class="bi bi-chevron-compact-right"></i></a>
<a href="{% url 'dashboard:submitted_applications' %}" class="item">Submitted Applications <i
        class="bi bi-chevron-compact-right"></i></a>
<a class="item">Review Application <i class="bi bi-chevron-compact-right"></i></a>
{%endblock%}


{% block content %}

<div class="col-md-10 mx-auto col-11">
    <div class="col-md-10 col-12 mx-auto">
        <div class="col-12 my-2">
            <h3 class="text text-center">Review</h3>
            <div class="col-md-6 col-12 mx-auto">
                <div class="progress-container mx-auto">
                    <div class="progress" id="progress" data-progress="100"></div>
                    <div class="circle-container">
                        <div class="circles active"><i class="bi bi-calendar"></i></div>
                        <span class="label text text-center text-primary">Particulars</span>
                    </div>
                    <div class="circle-container">
                        <div class="circles active"><i class="bi bi-graph-up"></i></div>
                        <span class="label text text-center text-primary">Ranks</span>
                    </div>
                    <div class="circle-container">
                        <div class="circles active"><i class="bi bi-house"></i></div>
                        <span class="label text text-center text-primary">Uploads</span>
                    </div>
                    <div class="circle-container">
                        <div class="circles active"><i class="bi bi-calendar"></i></div>
                        <span class="label text text-center text-primary">Review</span>
                    </div>
                </div>
            </div>

            {% include 'dashboard/blocks/application_review.html' %}

            <div class="form-group d-flex justify-content-between my-3">
                <button type="button" class="btn btn-primary py-2 px-4" onclick="history.back()"><i
                        class="bi bi-arrow-left"></i> Back</button>

                {% if application.status == 'draft' or application.status == 'requested_changes' or application.status == 'submitted'  %}
                <form method="POST" action="{% url 'dashboard:application_submission' application.id %}">
                    {% csrf_token %}
                    <input type="hidden" name="application_id" value="{{application.id}}">
                    <button class="btn btn-primary py-2 px-4" type="submit" style="width: 100%;"><i
                            class="bi bi-send"></i>
                        Submit</button>
                </form>
                {% endif %}

            </div>


        </div>
    </div>
</div>
{%endblock%}

dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css">
    <link rel="stylesheet" href="{% static 'css/dashboard_style.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard_style_res.css' %}">
    <link rel="shortcut icon" href="{% static 'images/logo.svg' %}" type="image/svg">
    <title>{% block pagetitle %}Home{%endblock%}</title>
</head>

<body>
    {% if messages %}
    <div class="alert-container col-md-6">
        <!-- message -->
        {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible fade show py-3 mt-1" role="alert">
            {{message}}
        </div>
        {% endfor %}
        <span class="close-btn" onclick="hideAlert()"><i class="bi bi-x-lg"></i></span>
    </div>
    {% endif %}
    <div class="overlay"></div>

    <main>
        <section class="sidebar overlay-toggle">
            <div class="header mt-1">
                <img src="{% static 'images/logo.svg' %}" alt="Site Logo">
                <div class="mx-2 info">
                    <p class="m-0 p-0 text text-center">{{request.user.username|title}}</p>
                    <p class="m-0 p-0 text text-center text-muted">{{request.user.get_title}}</p>
                </div>
            </div>
            <div class="content">
                <a href="{% url 'dashboard:index' %}" class="sidebar-item row">
                    <div class="col-2"><i class="bi bi-house"></i></div>
                    <div class="col-10">Home</div>
                </a>

                <a href="{% url 'dashboard:notifications' %}" class="sidebar-item row">
                    <div class="col-2"><i class="bi bi-bell"></i></div>
                    <div class="col-8">Notifications</div>
                    {% if request.user.count_notifications %}
                    <div class="col-2"><span class="balloon">{{request.user.notifications.count}}</span></div>
                    {% endif %}
                </a>

                {% if perms.dashboard.add_application %}
                <a href="{% url 'dashboard:my_applications' %}" class="sidebar-item row">
                    <div class="col-2"><i class="bi bi-window-stack"></i></div>
                    <div class="col-10">Application List</div>
                </a>
                {% endif %}

                {% if perms.dashboard.can_review_application %}
                <a href="{% url 'dashboard:submitted_applications' %}" class="sidebar-item row">
                    <div class="col-2"><i class="bi bi-window-stack"></i></div>
                    <div class="col-10">Submitted Applications</div>
                </a>
                {% endif %}

                {% if perms.setup.can_setup_system %}
                <a href="{% url 'setup:index' %}" class="sidebar-item row">
                    <div class="col-2"><i class="bi bi-gear"></i></div>
                    <div class="col-10">Setup</div>
                </a>
                {% endif %}

                <a href="{% url 'accounts:logout' %}" class="sidebar-item row">
                    <div class="col-2"><i class="bi bi-lock text text-warning"></i></div>
                    <div class="col-10"> <span class="text text-warning">Logout</span> </div>
                </a>

            </div>
        </section>

        <section class="main-page">
            <header>
                <nav id="main-nav">
                    <div class="ms-2 d-sm-block d-md-none" id="sidebar-toggle">
                        <span style="font-size: 2em;"><i class="bi bi-list"></i></span>
                    </div>

                    <div class="nav-right toggle-active" data-target=".nav-right .drop-down">
                        <div class="profile">
                            <img src="{% static 'images/logo.svg' %}" alt="Site Logo">
                            <div class="mx-2 info">
                                <span class="m-0 p-0 text">{{request.user.username|title}}</span>
                                <span class="m-0 p-0 text text-muted">{{request.user.get_title}}</span>
                            </div>
                            <i class="bi bi-chevron-down"></i>
                        </div>
                        <div class="drop-down">
                            <a href="" class="item"><i class="bi bi-person"></i> Profile</a>
                            <a href="{% url 'accounts:logout' %}" class="item"><i class="bi bi-lock"></i> Logout</a>
                        </div>
                    </div>
                </nav>
                <div class="breadcrum-container">
                    <div class="col-md-10 col-11 mx-auto">
                        {% block breadcrum %}
                        <a href="" class="item">Home <i class="bi bi-chevron-compact-right"></i></a>
                        <a href="" class="item">About <i class="bi bi-chevron-compact-right"></i></a>
                        {%endblock%}
                    </div>
                </div>
            </header>
            {% block content %}{%endblock%}

            <footer>
                <p>Copyright &copy;
                    <script>document.write(new Date().getFullYear())</script> All Rights Reserved
                </p>
            </footer>
        </section>
    </main>


    <!-- JavaScript Bundle with Popper -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
    <script src="{% static 'js/dashboard_utils.js' %}"></script>
    {% block morescripts %}{%endblock%}

</body>

</html>

dashboard/templates/dashboard/submitted_application_review_page.html
{% extends 'dashboard/base.html' %}
{% block pagetitle %}Application | Review{%endblock%}

{% block breadcrum %}
<a href="/" class="item">Home <i class="bi bi-chevron-compact-right"></i></a>
<a href="{% url 'dashboard:submitted_applications' %}" class="item">Submitted Applications <i
        class="bi bi-chevron-compact-right"></i></a>
<a class="item">Review Application <i class="bi bi-chevron-compact-right"></i></a>
{%endblock%}


{% block content %}

<!-- Request Changes Modal -->
<div class="modal fade" id="requestChangesModal" tabindex="-1" aria-labelledby="requestChangesModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-l">
        <div class="modal-content px-4">
            <div class="modal-header">
                <h5 class="modal-title" id="requestChangesModalLabel">Request changes to the application</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form class="my-2" action="{% url 'dashboard:request_changes' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="application_id" value="{{application.id}}">
                <label for="requested_changes">Changes <span class="text text-danger">*</span></label>
                <textarea class="form-control" name="requested_changes" id="requested_changes" cols="30" rows="10"
                    required></textarea>
                <button class="btn btn-primary my-3">Submit</button>
            </form>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<!-- End of Request Changes Modal -->


<div class="col-md-10 mx-auto col-11">
    <div class="col-md-10 col-12 mx-auto">
        <div class="col-12 my-2">
            <h3 class="text text-center">Application Details</h3>
            {% include 'dashboard/blocks/application_review.html' %}
            <div class="row">
                <div class="col-md-3 mt-3">
                    <a href="{% url 'dashboard:controller_form' application.id %}" class="btn btn-primary"><i
                            class="bi bi-pencil"></i> Complete Controller Form</a>
                </div>
                <div class="col-md-3 mt-3">
                    <a href="{% url 'pdf:generate_letter' application.id %}" target="_blank" class="btn btn-primary"><i
                            class="bi bi-printer"></i> Generate Letter</a>
                </div>
            </div>

            <div class="mt-3 card-shadow">
                <div class="row">
                    <h5 class="text text-primary">Feedback</h5>
                    {% if application.status == 'requested_changes' %}
                    <div class="col-12">
                        <p class="text text-danger">{{application.requested_changes}}</p>
                    </div>
                    {% endif %}
                    <form class="col-md-3" action="{% url 'dashboard:application_processed' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="application_id" value="{{application.id}}">
                        <button class="btn btn-success my-3"
                            {% if application.status == 'processed' %}disabled{% endif %}>
                            <i class="bi bi-check-lg"></i>
                            Approved and Processed
                        </button>
                    </form>
                    <div class="col-md-3">
                        <button type="button" class="btn btn-danger my-3" data-bs-toggle="modal"
                            data-bs-target="#requestChangesModal"><i class="bi bi-x-lg"></i> Request Changes</button>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{%endblock%}