dashboard/urls.py
from django.urls import path

from . import ajax, views

app_name = "dashboard"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("notifications",
         views.NotificationsView.as_view(),
         name="notifications"),
    path("apply",
         views.NewApplicationFormOneView.as_view(),
         name="application_form_one"),
    path("apply/add-ranks/<int:application_id>",
         views.NewApplicationAddRanksView.as_view(),
         name="application_form_ranks"),
    path("apply/upload/<int:application_id>",
         views.NewApplicationFormOneUploadView.as_view(),
         name="application_form_one_upload"),
    path("apply/upload-signature/<int:application_id>",
         views.UploadSignatureView.as_view(),
         name="upload_signature"),
    path("apply/review/<int:application_id>",
         views.NewApplicationFormOneReviewView.as_view(),
         name="application_form_one_review"),
    path("my-applications",
         views.MyApplicationsView.as_view(),
         name="my_applications"),
    path("submitted-applications",
         views.SubmittedApplicationsView.as_view(),
         name="submitted_applications"),
    path("submitted-application-review/<int:application_id>",
         views.SubmittedApplicationReviewView.as_view(),
         name="submitted_application_review"),
    path("delete-application",
         views.DeleteApplicationView.as_view(),
         name="delete_application"),
    path("application-details/<int:application_id>",
         views.ApplicationDetailsView.as_view(),
         name="application_details"),
    path("application-submission/<int:application_id>",
         views.ApplicationSubmissionView.as_view(),
         name="application_submission"),
    path("application-processed",
         views.ApplicationProcessedView.as_view(),
         name="application_processed"),
    path("request-changes",
         views.RequestApplicationChangesView.as_view(),
         name="request_changes"),
    path("controller-form/<int:application_id>/",
         views.ControllerFormView.as_view(),
         name="controller_form"),
    path("add-pensionable-emolument-before-retirement/<int:application_id>/",
         views.AddPensionableEmolumentDrawnBeforeRetirementView.as_view(),
         name="add_pensionable_emolument_before_retirement"),
    path("add-no-pay-leave/<int:application_id>/",
         views.AddNoPayLeaveView.as_view(),
         name="add_no_pay_leave"),
    path("add-service-break/<int:application_id>/",
         views.AddServiceBreakView.as_view(),
         name="add_service_break"),
    path("add-office-particulars/<int:application_id>/",
         views.AddOfficeParticularsView.as_view(),
         name="add_office_particulars"),
    path("add-paid-open-vote-service/<int:application_id>/",
         views.AddPaidOpenVoteServiceView.as_view(),
         name="add_paid_open_vote_service"),
    path("delete-pensionable-emolument/<int:pk>/",
         views.DeletePensionableEmolumentView.as_view(),
         name="delete_pensionable_emolument"),
    path("delete-no-pay-leave/<int:pk>/",
         views.DeleteNoPayLeaveView.as_view(),
         name="delete_no_pay_leave"),
    path("delete-service-break/<int:pk>/",
         views.DeletServiceBreakView.as_view(),
         name="delete_service_break"),
    path("delete-office-particulars/<int:pk>/",
         views.DeleteOfficeParticularsView.as_view(),
         name="delete_office_particulars"),
    path("delete-paid-open-vote-service/<int:pk>/",
         views.DeletePaidOpenVoteServiceView.as_view(),
         name="delete_paid_open_vote_service"),
    path("resend-sms", views.ResendSMSView.as_view(), name="resend_sms"),
]

urlpatterns += [
    path("ajax/upload-photo",
         ajax.UploadPhotoView.as_view(),
         name="upload_photo"),
    path("ajax/delete-application-document",
         ajax.ApplicationDocumentDeletionView.as_view(),
         name="delete_application_ducument")
]

setup/urls.py
from django.urls import path

from . import views

app_name = "setup"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("rank/change", views.CreateUpdateRank.as_view(), name="change_rank"),
    path("rank/delete", views.DeleteRank.as_view(), name="delete_rank"),
    path("document-type/change",
         views.CreateUpdateApplicationDocumentType.as_view(),
         name="change_document_type"),
    path("document-type/delete",
         views.DeleteApplicationDocumentType.as_view(),
         name="delete_document_type"),
    path("role/change", views.CreateUpdateGroup.as_view(), name="change_role"),
    path("role/delete", views.DeleteGroup.as_view(), name="delete_role"),
    path("user/delete", views.DeleteUser.as_view(), name="delete_user"),
    path("role/<int:role_id>/manage/",
         views.RoleManagementView.as_view(),
         name="manage_role"),
    path("user/change", views.CreateUpdateUser.as_view(), name="change_user"),
    path("retirement-reason/change",
         views.CreateUpdateRetirementReason.as_view(),
         name="change_retirement_reason"),
    path("retirement-reason/delete",
         views.DeleteRetirementReason.as_view(),
         name="delete_retirement_reason"),
    path("update-sysconfig",
         views.UpdateSysConfigView.as_view(),
         name="update_sysconfig"),
]

setup/models.py
from django.db import models


# Just for permissions
class SetupPerms(models.Model):
    class Meta:
        managed = False  # No database table creation or deletion  \
        # operations will be performed for this model.
        default_permissions = ()  # disable "add", "change", "delete"
        # and "view" default permissions
        permissions = (('can_setup_system', 'Can Setup System'),
                       ("can_managemnt_roles",
                        "Can Management role assignment user groups."))


class ApplicationDocumentType(models.Model):
    name = models.CharField(max_length=50)
    required = models.BooleanField(default=True)
    multiple = models.BooleanField(default=True)
    codename = models.CharField(max_length=50, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.codename:
            self.codename = "_".join(self.name.lower().split())
        return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name


class Rank(models.Model):
    name = models.CharField(max_length=100, unique=True)
    abbreviation = models.CharField(max_length=20, default="")
    order = models.IntegerField()

    def save(self, *args, **kwargs):
        if not self.abbreviation:
            self.abbreviation = self.name[:3].upper()
        return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name


class RetirementReason(models.Model):
    reason = models.TextField()
    description = models.TextField(null=True, blank=True)

    def __str__(self) -> str:
        return self.reason


class SysConfig(models.Model):
    sms_sender_id = models.CharField(max_length=11,
                                     unique=True,
                                     default="GHPOLPEN")
    send_sms = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.name

setup/forms.py
from django import forms
from django.contrib.auth.models import Group

from accounts.models import User
from setup.models import ApplicationDocumentType, Rank, RetirementReason


class RankForm(forms.ModelForm):
    class Meta:
        model = Rank
        exclude = [
            "id",
        ]


class ApplicationDocumentTypeForm(forms.ModelForm):
    class Meta:
        model = ApplicationDocumentType
        exclude = [
            "id",
            'codename',
            "created_at",
            "updated_at",
        ]


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = [
            'name',
        ]


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        exclude = [
            "id",
            'photo',
            'email',
            'gender',
            'password',
            'last_login',
            "created_at",
            "updated_at",
        ]


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        exclude = [
            "id",
            'photo',
            'email',
            'password',
            "username",
            'gender',
            'last_login',
            "created_at",
            "updated_at",
        ]


class RetirementReasonForm(forms.ModelForm):
    class Meta:
        model = RetirementReason
        exclude = [
            "id",
        ]

setup/views.py
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import Group, Permission
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.views import View

from accounts.models import User
from setup.forms import (ApplicationDocumentTypeForm, GroupForm, RankForm,
                         RetirementReasonForm, UserEditForm, UserForm)
from setup.models import (ApplicationDocumentType, Rank, RetirementReason,
                          SysConfig)
from setup.mxins import CreateUpdateMixin, DeletionMixin


class IndexView(PermissionRequiredMixin, View):
    template_name = "setup/index.html"
    permission_required = ("setup.can_setup_system", )

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request):
        document_types = ApplicationDocumentType.objects.all()
        ranks = Rank.objects.all().order_by("order")
        roles = Group.objects.all()
        users = User.objects.filter(is_superuser=False)
        reasons = RetirementReason.objects.all()
        config = SysConfig.objects.first()

        context = {
            "document_types": document_types,
            "ranks": ranks,
            "roles": roles,
            "config": config,
            "users": users,
            "reasons": reasons,
            "user": None,
        }
        return render(request, self.template_name, context)


class CreateUpdateRank(PermissionRequiredMixin, CreateUpdateMixin):
    template_name = "setup/edit_rank.html"
    form_class = RankForm
    object_id_field = "rank_id"
    model_class = Rank
    object_name = "rank"
    permission_required = (
        "setup.can_setup_system",
        "setup.add_rank",
        "setup.change_rank",
    )


class DeleteRank(PermissionRequiredMixin, DeletionMixin):
    object_id_field = "rank_id"
    model_class = Rank
    permission_required = (
        "setup.can_setup_system",
        "setup.delete_rank",
    )


class CreateUpdateApplicationDocumentType(PermissionRequiredMixin,
                                          CreateUpdateMixin):
    template_name = "setup/edit_application_document_type.html"
    form_class = ApplicationDocumentTypeForm
    object_id_field = "document_type_id"
    model_class = ApplicationDocumentType
    object_name = "document_type"
    permission_required = (
        "setup.can_setup_system",
        "setup.add_applicationdocumenttype",
        "setup.change_applicationdocumenttype",
    )


class DeleteApplicationDocumentType(PermissionRequiredMixin, DeletionMixin):
    object_id_field = "document_type_id"
    model_class = ApplicationDocumentType
    permission_required = (
        "setup.can_setup_system",
        "setup.delete_applicationdocumenttype",
    )


class CreateUpdateGroup(PermissionRequiredMixin, CreateUpdateMixin):
    template_name = "setup/edit_role.html"
    form_class = GroupForm
    object_id_field = "role_id"
    model_class = Group
    object_name = "role"
    permission_required = (
        "setup.can_setup_system",
        "auth.add_group",
        "auth.change_group",
    )


class DeleteGroup(PermissionRequiredMixin, DeletionMixin):
    object_id_field = "role_id"
    model_class = Group
    permission_required = (
        "setup.can_setup_system",
        "auth.delete_group",
    )


class DeleteUser(PermissionRequiredMixin, DeletionMixin):
    object_id_field = "user_id"
    model_class = User
    permission_required = (
        "setup.can_setup_system",
        "accounts.delete_user",
    )


class RoleManagementView(PermissionRequiredMixin, View):
    template_name = "setup/role_management.html"
    permission_required = (
        "setup.can_managemnt_roles",
        "setup.can_setup_system",
    )

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request, role_id):
        role = get_object_or_404(Group, id=role_id)
        permissions = Permission.objects.filter()[:0]
        apps_list = [app.split(".")[0] for app in settings.INSTALLED_APPS]
        models = []
        for app in apps_list:
            models.extend([
                model._meta.model_name
                for _, model in apps.all_models[app].items()
            ])
        permissions = Permission.objects.filter(
            content_type__app_label__in=apps_list,
            content_type__model__in=models)
        permissions = Permission.objects.all()
        context = {
            "role": role,
            "permissions": permissions,
        }
        return render(request, self.template_name, context)

    @method_decorator(login_required(login_url="accounts:login"))
    def post(self, request, role_id):
        role = get_object_or_404(Group, id=role_id)
        permissions_codes = request.POST.getlist("permissions")
        permissions = Permission.objects.filter(codename__in=permissions_codes)
        role.permissions.set(permissions)
        return redirect(request.META.get("HTTP_REFERER") or "setup:dashboard")


class CreateUpdateUser(PermissionRequiredMixin, CreateUpdateMixin):
    template_name = "setup/edit_user.html"
    object_id_field = "user_id"
    form_class = UserForm
    edit_form_class = UserEditForm
    model_class = User
    object_name = "user"
    permission_required = (
        "setup.can_setup_system",
        "accounts.add_user",
        "accounts.change_user",
    )

    def get(self, request):
        object_id = request.GET.get(self.object_id_field)
        obj = get_object_or_404(self.model_class, id=object_id)
        roles = Group.objects.all()
        context = {
            self.object_name: obj,
            "roles": roles,
        }
        return render(request, self.template_name, context)

    @method_decorator(login_required(login_url="accounts:login"))
    def post(self, request):
        user_id = request.POST.get("user_id") or None
        password = request.POST.get("password")
        username = request.POST.get("username")
        group_ids = request.POST.getlist("groups")
        conf_password = request.POST.get("conf_password")

        groups = Group.objects.filter(id__in=group_ids)

        if password and password != conf_password:
            messages.error(request, "Passwords do not match")
            return redirect(request.META.get("HTTP_REFERER") or "setup:index")

        user = User.objects.filter(
            id=user_id).first() or User.objects.create_user(username=username,
                                                            password=password)
        # Add to groups
        user.groups.set(groups)

        # Update fields
        for key, value in request.POST.items():
            if key in ["password", "username", "groups"]: continue
            if value and key and hasattr(user, key):
                setattr(user, key, value)
        if password: user.set_password(password)
        user.save()
        messages.success(request, "User updated successfully")
        return redirect("setup:index")


class CreateUpdateRetirementReason(PermissionRequiredMixin, CreateUpdateMixin):
    template_name = "setup/edit_retirement_reason.html"
    form_class = RetirementReasonForm
    object_id_field = "retirement_reason_id"
    model_class = RetirementReason
    object_name = "retirement_reason"
    permission_required = (
        "setup.can_setup_system",
        "setup.add_retirementreason",
        "setup.change_retirementreason",
    )


class DeleteRetirementReason(PermissionRequiredMixin, DeletionMixin):
    object_id_field = "retirement_reason_id"
    model_class = RetirementReason
    permission_required = (
        "setup.can_setup_system",
        "setup.delete_retirement_reason",
    )


class UpdateSysConfigView(PermissionRequiredMixin, View):
    permission_required = ("setup.can_setup_system", )

    def get(self, request, *args, **kwargs):
        return redirect("setup:index")

    @method_decorator(login_required(login_url="accounts:login"))
    def post(self, request, *args, **kwargs):
        config = SysConfig.objects.first()
        if "sms_sender_id" in request.POST and not "send_sms" in request.POST:
            config.send_sms = False
            config.save()
        for key, value in request.POST.items():
            if key in ["csrfmiddlewaretoken", "submit"]: continue
            if key == "send_sms":
                value = True if value == "on" else False
            if value and hasattr(config, key):
                setattr(config, key, value)
        config.save()
        messages.success(request, "System configuration updated successfully")
        return redirect("setup:index")

setup/templates/setup/edit_application_document_type.html
{% extends 'dashboard/base.html' %}
<title>{% block pagetitle %}Setup | Edit Document Type{%endblock%}</title>

{% block breadcrum %}
<a href="{% url 'dashboard:index' %}" class="item">Home <i class="bi bi-chevron-compact-right"></i></a>
<a href="{% url 'setup:index' %}" class="item">Setup <i class="bi bi-chevron-compact-right"></i></a>
<a href="" class="item">Edit Document Type<i class="bi bi-chevron-compact-right"></i></a>
{%endblock%}

{% block content %}

<div class="row col-md-11 mx-auto">
    <section class="col-md-6 mx-auto">
        <div class="card-shadow">
            <div class="d-flex justify-content-between">
                <h6>DOCUMENT TYPE</h6>
            </div>
            {% include 'setup/blocks/forms/form_document_type.html' %}
        </div>
    </section>
</div>
{%endblock%}

setup/templates/setup/edit_rank.html
{% extends 'dashboard/base.html' %}
<title>{% block pagetitle %}Setup | Edit Rank{%endblock%}</title>

{% block breadcrum %}
<a href="{% url 'dashboard:index' %}" class="item">Home <i class="bi bi-chevron-compact-right"></i></a>
<a href="{% url 'setup:index' %}" class="item">Setup <i class="bi bi-chevron-compact-right"></i></a>
<a href="" class="item">Edit Rank<i class="bi bi-chevron-compact-right"></i></a>
{%endblock%}

{% block content %}

<div class="row col-md-11 mx-auto">
    <section class="col-md-6 mx-auto">
        <div class="card-shadow">
            <div class="d-flex justify-content-between">
                <h6>RANKS</h6>
            </div>
            {% include 'setup/blocks/forms/form_rank.html' %}
        </div>
    </section>
</div>
{%endblock%}

setup/templates/setup/edit_retirement_reason.html
{% extends 'dashboard/base.html' %}
<title>{% block pagetitle %}Setup | Edit Retirement Reason{%endblock%}</title>

{% block breadcrum %}
<a href="{% url 'dashboard:index' %}" class="item">Home <i class="bi bi-chevron-compact-right"></i></a>
<a href="{% url 'setup:index' %}" class="item">Setup <i class="bi bi-chevron-compact-right"></i></a>
<a href="" class="item">Edit Retirement Reason<i class="bi bi-chevron-compact-right"></i></a>
{%endblock%}

{% block content %}

<div class="row col-md-11 mx-auto">
    <section class="col-md-6 mx-auto">
        <div class="card-shadow">
            <div class="d-flex justify-content-between">
                <h6>RETIREMENT REASON</h6>
            </div>
            {% include 'setup/blocks/forms/form_retirement_reason.html' %}
        </div>
    </section>
</div>
{%endblock%}

setup/templates/setup/edit_role.html
{% extends 'dashboard/base.html' %}
<title>{% block pagetitle %}Setup | Edit Role{%endblock%}</title>

{% block breadcrum %}
<a href="{% url 'dashboard:index' %}" class="item">Home <i class="bi bi-chevron-compact-right"></i></a>
<a href="{% url 'setup:index' %}" class="item">Setup <i class="bi bi-chevron-compact-right"></i></a>
<a href="" class="item">Edit Role<i class="bi bi-chevron-compact-right"></i></a>
{%endblock%}

{% block content %}

<div class="row col-md-11 mx-auto">
    <section class="col-md-6">
        <div class="card-shadow">
            <div class="d-flex justify-content-between">
                <h6>ROLES</h6>
            </div>
            {% include 'setup/blocks/forms/form_role.html' %}
        </div>
    </section>
</div>
{%endblock%}

setup/templates/setup/edit_user.html
{% extends 'dashboard/base.html' %}
<title>{% block pagetitle %}Setup | Edit User{%endblock%}</title>

{% block breadcrum %}
<a href="{% url 'dashboard:index' %}" class="item">Home <i class="bi bi-chevron-compact-right"></i></a>
<a href="{% url 'setup:index' %}" class="item">Setup <i class="bi bi-chevron-compact-right"></i></a>
<a href="" class="item">Edit User<i class="bi bi-chevron-compact-right"></i></a>
{%endblock%}

{% block content %}

<div class="row col-md-11 mx-auto">
    <section class="col-md-6 mx-auto">
        <div class="card-shadow">
            <div class="d-flex justify-content-between">
                <h6>USER</h6>
            </div>
            {% include 'setup/blocks/forms/form_user.html' %}
        </div>
    </section>
</div>
{%endblock%}

setup/templates/setup/role_management.html
{% extends 'dashboard/base.html' %}
<title>{% block pagetitle %}Setup | Edit Role{%endblock%}</title>

{% block breadcrum %}
<a href="{% url 'dashboard:index' %}" class="item">Home <i class="bi bi-chevron-compact-right"></i></a>
<a href="{% url 'setup:index' %}" class="item">Setup <i class="bi bi-chevron-compact-right"></i></a>
<a href="" class="item">Role Management<i class="bi bi-chevron-compact-right"></i></a>
{%endblock%}

{% block content %}

<div class="row col-md-11 mx-auto">
    <div class="card-shadow">
        <div>
            <h6>ROLE MANAGEMENT</h6>
            <p class="text text-muted">{{role.name}}</p>
        </div>

        <form action="" method="POST">
            {% csrf_token %}
            <div class="col-md-6 mx-auto">
                <table class="table table-sm">
                    <caption>List of permissions</caption>
                    <thead>
                        <tr>
                            <th>Permission</th>
                            <th>Has Permission</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for permission in permissions %}
                        <tr>
                            <td>{{permission.name}}</td>
                            <td>
                                <input type="checkbox" name="permissions" value="{{permission.codename}}"
                                    {% if permission in role.permissions.all %}checked{% endif %}>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="col-md-6 mx-auto">
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </form>

    </div>
</div>
{%endblock%}